# FROM almalinux:8
# LABEL TRAINING ="DEVOPS" \
#       TRAINER ="sivakumar" \
#       DURATION="120HRS"


FROM almalinux:8
LABEL TRAINING="DEVOPS" \
      TRAINER="Sivakumar" \
      DURATION="120HRS" \