# FROM almalinux:8
# LABEL TRAINING="DEVOPS" \
#       TRAINER="Charankumar" \
#       DURATION="120HRS"


# FROM almalinux:8
# LABEL TRAINING="DEVOPS" \
#       TRAINER="Sivakumar" \
#       DURATION="120HRS" \

FROM almalinux:8
LABEL TRAINING="DEVOPS" \
      TRAINER="Kirankumar" \
      DURATION="120HRS" \
      org.opencontainers.image.authors="info@charan.fun"
