FROM almalinux:8
RUN yum install nginx -y
RUN rm -rf /usr/share/nginx/html/index.html
COPY index.html /usr/share/nginx/html
ADD https://raw.githubusercontent.com/charankumarPadeti/test-repo/refs/heads/master/example.txt /tmp/
CMD ["nginx","-g","daemon off;"]